version: 0.1.1-{build}

skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\feembox

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;C:\Users\appveyor\.cargo\bin
  -
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Sy pacman"
  - bash -lc "pacman --noconfirm -Su"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  -
  - curl -SL https://win.rustup.rs/ -oC:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host="x86_64-pc-windows-gnu"

build: off
build_script:
  - cargo build --verbose --release
  -
  - cp target\release\feembox.exe feembox-v0.1.1.exe
  - strip --strip-all --remove-section=.comment --remove-section=.note feembox-v0.1.1.exe

test: off
test_script:
  - cargo test --verbose --release

artifacts:
  - path: feembox-v0.1.1.exe

deploy:
  provider: GitHub
  artifact: /.*\.exe/
  auth_token:
    secure: wKX6409NXAIn0vsb8Pb+x0cwdrcZQbtvLhECQDJngVlmkn5wdLiGKcZ5NYlbaTI+
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    on_build_status_changed: true
